### ISSUE TITLE
Put this on Netlify 😎

### ISSUE THREAD

**Issue by bdougie** [DrianHillman/spotless-app#2]
Hey Heads up, I am going to talk about this project a bit tomorrow in a Ruby Meetup. Any chance you can deploy the app to Netlify. I noticed that the heroku app takes some time to load a cold start. That wouldn't happen with Netlify, I tested it :) - https://juggler-reveille-50025.netlify.com/

**Comment by DrianHillman** [comment]
You bet— I've published this to Netlify! 👍🏽 
> https://spotless-app.netlify.com/

All the best on your talk tomorrow, @bdougie!
